FROM node:25-alpine AS build 
WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .
RUN npm run build

#stage 2
FROM nginx:stable-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]